### ISSUE TITLE
Mod disables on load

### ISSUE THREAD

**Issue by Ekinn7188** [Pbone3/PboneUtils#20]
When I try to load this mod, I get the following error:

```
[14:12:53] [35/ERROR] [tML]: An error occurred while loading PboneUtils
The mod(s) have been automatically disabled.
System.InvalidOperationException: Return type of hook for Int32 QuickSpawnItem(Int32, Int32) doesn't match, must be System.Int32
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig& config)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig config)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase method, Delegate to)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint._NewHook(MethodBase from, Delegate to)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint._Add[TDelegate](Func`3 gen, TDelegate hookDelegate)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint.Add(Delegate hookDelegate)
   at MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Add(MethodBase method, Delegate hookDelegate)
   at MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Add[T](MethodBase method, Delegate hookDelegate)
   at On.Terraria.Player.add_QuickSpawnItem_int_int(hook_QuickSpawnItem_int_int )
   at PboneUtils.PboneUtils.Load_On() in PboneUtils.On.cs:line 13
   at PboneUtils.PboneUtils.Load() in PboneUtils.cs:line 61
   at Terraria.ModLoader.ModContent.<>c.<Load>b__41_0(Mod mod) in tModLoader\Terraria\ModLoader\ModContent.cs:line 303
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction) in tModLoader\Terraria\ModLoader\ModContent.cs:line 358
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 297
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 130
[14:12:53] [35/INFO] [tML]: Disabling Mod: PboneUtils
```

I tried restarting the game, but it never wants to load

**Comment by Ekinn7188** [comment]
The next day it worked :)
